/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedSpraysRouteImport } from './routes/_authed/sprays'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedSearchRouteImport } from './routes/_authed/search'
import { Route as AuthedExportRouteImport } from './routes/_authed/export'
import { Route as AuthedCalculatorRouteImport } from './routes/_authed/calculator'
import { Route as AuthedAboutRouteImport } from './routes/_authed/about'
import { Route as AuthedFieldsIndexRouteImport } from './routes/_authed/fields/index'
import { Route as AuthedPesticideIdRouteImport } from './routes/_authed/pesticide/$id'
import { Route as AuthedFieldsNewRouteImport } from './routes/_authed/fields/new'
import { Route as AuthedFieldsFieldIdRouteImport } from './routes/_authed/fields/$fieldId'
import { Route as AuthedDemoTanstackQueryRouteImport } from './routes/_authed/demo/tanstack-query'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSpraysRoute = AuthedSpraysRouteImport.update({
  id: '/sprays',
  path: '/sprays',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSearchRoute = AuthedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedExportRoute = AuthedExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCalculatorRoute = AuthedCalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAboutRoute = AuthedAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedFieldsIndexRoute = AuthedFieldsIndexRouteImport.update({
  id: '/fields/',
  path: '/fields/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPesticideIdRoute = AuthedPesticideIdRouteImport.update({
  id: '/pesticide/$id',
  path: '/pesticide/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedFieldsNewRoute = AuthedFieldsNewRouteImport.update({
  id: '/fields/new',
  path: '/fields/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedFieldsFieldIdRoute = AuthedFieldsFieldIdRouteImport.update({
  id: '/fields/$fieldId',
  path: '/fields/$fieldId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDemoTanstackQueryRoute = AuthedDemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/about': typeof AuthedAboutRoute
  '/calculator': typeof AuthedCalculatorRoute
  '/export': typeof AuthedExportRoute
  '/search': typeof AuthedSearchRoute
  '/settings': typeof AuthedSettingsRoute
  '/sprays': typeof AuthedSpraysRoute
  '/demo/tanstack-query': typeof AuthedDemoTanstackQueryRoute
  '/fields/$fieldId': typeof AuthedFieldsFieldIdRoute
  '/fields/new': typeof AuthedFieldsNewRoute
  '/pesticide/$id': typeof AuthedPesticideIdRoute
  '/fields/': typeof AuthedFieldsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/about': typeof AuthedAboutRoute
  '/calculator': typeof AuthedCalculatorRoute
  '/export': typeof AuthedExportRoute
  '/search': typeof AuthedSearchRoute
  '/settings': typeof AuthedSettingsRoute
  '/sprays': typeof AuthedSpraysRoute
  '/': typeof AuthedIndexRoute
  '/demo/tanstack-query': typeof AuthedDemoTanstackQueryRoute
  '/fields/$fieldId': typeof AuthedFieldsFieldIdRoute
  '/fields/new': typeof AuthedFieldsNewRoute
  '/pesticide/$id': typeof AuthedPesticideIdRoute
  '/fields': typeof AuthedFieldsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/about': typeof AuthedAboutRoute
  '/_authed/calculator': typeof AuthedCalculatorRoute
  '/_authed/export': typeof AuthedExportRoute
  '/_authed/search': typeof AuthedSearchRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/sprays': typeof AuthedSpraysRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/demo/tanstack-query': typeof AuthedDemoTanstackQueryRoute
  '/_authed/fields/$fieldId': typeof AuthedFieldsFieldIdRoute
  '/_authed/fields/new': typeof AuthedFieldsNewRoute
  '/_authed/pesticide/$id': typeof AuthedPesticideIdRoute
  '/_authed/fields/': typeof AuthedFieldsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/about'
    | '/calculator'
    | '/export'
    | '/search'
    | '/settings'
    | '/sprays'
    | '/demo/tanstack-query'
    | '/fields/$fieldId'
    | '/fields/new'
    | '/pesticide/$id'
    | '/fields/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/about'
    | '/calculator'
    | '/export'
    | '/search'
    | '/settings'
    | '/sprays'
    | '/'
    | '/demo/tanstack-query'
    | '/fields/$fieldId'
    | '/fields/new'
    | '/pesticide/$id'
    | '/fields'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/about'
    | '/_authed/calculator'
    | '/_authed/export'
    | '/_authed/search'
    | '/_authed/settings'
    | '/_authed/sprays'
    | '/_authed/'
    | '/_authed/demo/tanstack-query'
    | '/_authed/fields/$fieldId'
    | '/_authed/fields/new'
    | '/_authed/pesticide/$id'
    | '/_authed/fields/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/sprays': {
      id: '/_authed/sprays'
      path: '/sprays'
      fullPath: '/sprays'
      preLoaderRoute: typeof AuthedSpraysRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/search': {
      id: '/_authed/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthedSearchRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/export': {
      id: '/_authed/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof AuthedExportRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/calculator': {
      id: '/_authed/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof AuthedCalculatorRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/about': {
      id: '/_authed/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthedAboutRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/fields/': {
      id: '/_authed/fields/'
      path: '/fields'
      fullPath: '/fields/'
      preLoaderRoute: typeof AuthedFieldsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/pesticide/$id': {
      id: '/_authed/pesticide/$id'
      path: '/pesticide/$id'
      fullPath: '/pesticide/$id'
      preLoaderRoute: typeof AuthedPesticideIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/fields/new': {
      id: '/_authed/fields/new'
      path: '/fields/new'
      fullPath: '/fields/new'
      preLoaderRoute: typeof AuthedFieldsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/fields/$fieldId': {
      id: '/_authed/fields/$fieldId'
      path: '/fields/$fieldId'
      fullPath: '/fields/$fieldId'
      preLoaderRoute: typeof AuthedFieldsFieldIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/demo/tanstack-query': {
      id: '/_authed/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof AuthedDemoTanstackQueryRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAboutRoute: typeof AuthedAboutRoute
  AuthedCalculatorRoute: typeof AuthedCalculatorRoute
  AuthedExportRoute: typeof AuthedExportRoute
  AuthedSearchRoute: typeof AuthedSearchRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedSpraysRoute: typeof AuthedSpraysRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedDemoTanstackQueryRoute: typeof AuthedDemoTanstackQueryRoute
  AuthedFieldsFieldIdRoute: typeof AuthedFieldsFieldIdRoute
  AuthedFieldsNewRoute: typeof AuthedFieldsNewRoute
  AuthedPesticideIdRoute: typeof AuthedPesticideIdRoute
  AuthedFieldsIndexRoute: typeof AuthedFieldsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAboutRoute: AuthedAboutRoute,
  AuthedCalculatorRoute: AuthedCalculatorRoute,
  AuthedExportRoute: AuthedExportRoute,
  AuthedSearchRoute: AuthedSearchRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedSpraysRoute: AuthedSpraysRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedDemoTanstackQueryRoute: AuthedDemoTanstackQueryRoute,
  AuthedFieldsFieldIdRoute: AuthedFieldsFieldIdRoute,
  AuthedFieldsNewRoute: AuthedFieldsNewRoute,
  AuthedPesticideIdRoute: AuthedPesticideIdRoute,
  AuthedFieldsIndexRoute: AuthedFieldsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
